# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Kerry Gallagher
description: > # this means to ignore newlines until "baseurl:"
 Web Developer based in Newcastle upon Tyne. Loves animals, food and games.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site
twitter_username: Kerry350
github_username:  Kerry350

# Build settings
markdown: kramdown

gems:
 - jekyll-paginate

paginate: 5
